PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/f5912b5cbad3b7a731231d778ccc101da6f3c353

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/a96d05c286fc1c619111f220e500b14e18c0509c) in current PX4/master (1eb7809eb55a50690a08bcba8cd553a22a9a412c)
https://github.com/PX4/NuttX/compare/a96d05c286fc1c619111f220e500b14e18c0509c...f5912b5cbad3b7a731231d778ccc101da6f3c353

f5912b5cba (HEAD, origin/master) arch: samd5e5 : Oneshot, freerun and tickless available support. All support runs on Timer/Counter (TC). Some fixes in external interrupt controller (EIC) and clockconfig.
171cc38ac2 arch: samd5e5 : Add watchdog timer drivers.
a7a81b5126 libc: Replace all [nx]sem_xxx with _SEM_XXX
8db91a7974 timers/timer.c:397:19: Fix warning: implicit declaration of function 'timer_setcallback'
3d0cdc3d95 sim/loadable: Remove CONFIG_USERMAIN_STACKSIZE from defconfig
6176e33ed2 fs/littlefs: enable the low level log only on debug mode
b89737395b vfs/epoll: add epoll_create1(2) implement
2e2ebb95ca sys/poll/epoll: sync the epoll_event struct layout with pollfd
155860ad15 sys/epoll: move the private handle to epoll_data_t
f97b8436b3 drivers/bch: flush the dirty sector to keep the sector sequence

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/78e8090842bbd3123a58629e94d30144954f6ef4

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (1eb7809eb55a50690a08bcba8cd553a22a9a412c)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...78e8090842bbd3123a58629e94d30144954f6ef4

78e80908 (HEAD -> master, origin/master) examples: wget: Fix nxstyle issues
10386cf5 examples/wget: wget example to work without NSH_NETINIT config
7a1d6265 netutils/webclient: Enable to send long HTTP request
18158ed2 system: add libuv port for NuttX
74c506b4 nsh: Don't check CONFIG_NFILE_STREAMS for mkdir/rename/rmdir/fs_unlink
e71e537e ftpc_transfer.c:667:15: Fix error: ‘argc’ undeclared
aaa198f0 interpreters/duktape: Clean objects
08c59984 graphics/lvgl: Specific LVGL version by kconfig
7099bc4b interpreters/duktape: Add console/print/alart support
efeb1d10 netutils/ftpc: Change watchdog callback prototype